// Builds src/client/monsters/icons.ts, the creatures in the GM's Monsters list, from the
// game-icons.net SVGs in scripts/monster-icons/svg and the table in scripts/monster-icons/list.tsv
// (id, name, game-icons.net author/icon, D&D size, creature type). Each icon must be one path
// on a 512 x 512 view box. Also works out where each icon's drawing sits in that box (the middle
// of its bounding box, and how far from there its farthest painted pixel is), so the token art
// can centre it and keep it inside the disc. To add a creature: put its SVG in the folder, add a
// line to list.tsv, and run `node scripts/monster-icons.mjs`. Uses sharp (installed with the Cloudflare tools, through miniflare).

import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(root, "package.json"));
const sharp = require("sharp");

const SOURCE = process.argv[2] ?? join(root, "scripts", "monster-icons");
const OUT = join(root, "src", "client", "monsters", "icons.ts");
const SIZES = ["tiny", "small", "medium", "large", "huge", "gargantuan"];
const TYPES = ["humanoid", "undead", "beast", "monstrosity", "giant", "dragon", "fiend", "elemental", "construct", "plant", "fey"];

/** The painted part of an icon: its bounding box's middle, and the farthest painted pixel from there. */
async function fitOf(svg) {
  const { data, info } = await sharp(Buffer.from(svg)).resize(512, 512).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const alpha = (x, y) => data[(y * info.width + x) * info.channels + 3];
  let x0 = 512, y0 = 512, x1 = -1, y1 = -1;
  for (let y = 0; y < 512; y++) {
    for (let x = 0; x < 512; x++) {
      if (alpha(x, y) < 64) continue;
      x0 = Math.min(x0, x);
      y0 = Math.min(y0, y);
      x1 = Math.max(x1, x + 1);
      y1 = Math.max(y1, y + 1);
    }
  }
  if (x1 < 0) throw new Error("nothing painted");
  const cx = (x0 + x1) / 2;
  const cy = (y0 + y1) / 2;
  let r = 0;
  for (let y = 0; y < 512; y++) {
    for (let x = 0; x < 512; x++) {
      if (alpha(x, y) >= 64) r = Math.max(r, Math.hypot(x + 0.5 - cx, y + 0.5 - cy));
    }
  }
  const round = (v) => Math.round(v * 10) / 10;
  return [round(cx), round(cy), round(r + 0.5)];
}

const rows = readFileSync(join(SOURCE, "list.tsv"), "utf8")
  .split(/\r?\n/)
  .filter((l) => l.trim())
  .map((l) => l.split("\t"));

const ids = new Set();
const icons = [];
for (const [id, name, source, size, type] of rows) {
  if (!/^[a-z0-9-]+$/.test(id) || ids.has(id)) throw new Error(`${id}: bad or repeated id`);
  if (!SIZES.includes(size)) throw new Error(`${id}: unknown size ${size}`);
  if (!TYPES.includes(type)) throw new Error(`${id}: unknown type ${type}`);
  ids.add(id);
  const svg = readFileSync(join(SOURCE, "svg", `${id}.svg`), "utf8");
  if (!svg.includes('viewBox="0 0 512 512"')) throw new Error(`${id}: not a 512 x 512 icon`);
  if (/transform|<(g|circle|rect|ellipse|polygon|polyline|line|use)\b/.test(svg)) throw new Error(`${id}: more than one plain path`);
  const paths = [...svg.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`${id}: ${paths.length} paths`);
  icons.push({ id, name, size, type, source, fit: await fitOf(svg), path: paths[0] });
}

const lines = [
  "// Generated by scripts/monster-icons.mjs from scripts/monster-icons: don't edit by hand.",
  "// Icons from game-icons.net by Lorc, Delapouite, Caro Asercion, Cathelineau and Skoll,",
  "// under CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/). See CREDITS.md.",
  "",
  'import type { MonsterIcon } from "./monsters";',
  "",
  "export const MONSTER_ICONS: readonly MonsterIcon[] = [",
  ...icons.map(
    (m) =>
      `  { id: ${JSON.stringify(m.id)}, name: ${JSON.stringify(m.name)}, size: ${JSON.stringify(m.size)}, type: ${JSON.stringify(m.type)}, ` +
      `source: ${JSON.stringify(m.source)}, fit: [${m.fit.join(", ")}], path: ${JSON.stringify(m.path)} },`,
  ),
  "];",
  "",
];
writeFileSync(OUT, lines.join("\n"));
console.log(`${icons.length} creatures written to ${OUT}`);
