// Generated by scripts/npc-icons.mjs from scripts/npc-icons/list.tsv: don't edit by hand.
// The races and classes are the group's own, from its campaign handbook. See CREDITS.md.

import type { NpcClass, NpcRace } from "./npcs";

/** The races in the order the list shows them (within each group). */
export const NPC_RACES: readonly NpcRace[] = [
  { id: "nyloran", name: "Nyloran", group: "Elves", size: "medium", icon: "delapouite_woman-elf-face", tint: "#f3e9dc" },
  { id: "sylvan", name: "Sylvan", group: "Elves", size: "medium", icon: "delapouite_woman-elf-face", tint: "#d08b57" },
  { id: "duga", name: "Duga", group: "Elves", size: "medium", icon: "delapouite_woman-elf-face", tint: "#e2b48a" },
  { id: "half-elf", name: "Half-elf", group: "Elves", size: "medium", icon: "delapouite_elf-ear", tint: "#eadfcf" },
  { id: "dwerv", name: "Dwerv", group: "Dwerves and gnomes", size: "medium", icon: "delapouite_dwarf-face", tint: "#ecc9a0" },
  { id: "gnome", name: "Gnome", group: "Dwerves and gnomes", size: "small", icon: "cathelineau_bad-gnome", tint: "#f1e2c8" },
  { id: "oesir", name: "Oesir", group: "Humans", size: "medium", icon: "delapouite_viking-head", tint: "#f6ecd2" },
  { id: "firgald", name: "Firgald", group: "Humans", size: "medium", icon: "delapouite_closed-barbute", tint: "#e7e1d6" },
  { id: "wyddin", name: "Wyddin", group: "Humans", size: "medium", icon: "delapouite_character", tint: "#e8d3b8" },
  { id: "danae", name: "Danae", group: "Humans", size: "medium", icon: "delapouite_robin-hood-hat", tint: "#f0c4a0" },
  { id: "octran", name: "Octran", group: "Humans", size: "medium", icon: "lorc_crested-helmet", tint: "#e9cf9c" },
  { id: "goblin", name: "Goblin", group: "NPC races", size: "small", icon: "caro-asercion_goblin", tint: "#b9d98a" },
  { id: "hobgoblin", name: "Hobgoblin", group: "NPC races", size: "medium", icon: "delapouite_goblin-head", tint: "#e0a070" },
  { id: "lizardfolk", name: "Lizardfolk", group: "NPC races", size: "medium", icon: "lorc_lizardman", tint: "#a8d08a" },
  { id: "kobold", name: "Kobold", group: "NPC races", size: "small", icon: "lorc_lizardman", tint: "#d8b06a" },
  { id: "sea-elf", name: "Sea Elf", group: "NPC races", size: "medium", icon: "delapouite_woman-elf-face", tint: "#8fd4c6" },
  { id: "urk", name: "Urk", group: "NPC races", size: "medium", icon: "delapouite_orc-head", tint: "#a9c48a" },
];

/** The classes in the order the list shows them (within each group). */
export const NPC_CLASSES: readonly NpcClass[] = [
  { id: "fighter", name: "Fighter", group: "Classes", icon: "lorc_crossed-swords", color: "#d9534f" },
  { id: "crusader", name: "Crusader", group: "Classes", icon: "delapouite_templar-shield", color: "#f0c040" },
  { id: "samurai", name: "Samurai", group: "Classes", icon: "delapouite_katana", color: "#e0573c" },
  { id: "ranger", name: "Ranger", group: "Classes", icon: "delapouite_bow-arrow", color: "#5cb85c" },
  { id: "cleric", name: "Cleric", group: "Classes", icon: "lorc_holy-symbol", color: "#f5e6a8" },
  { id: "war-cleric", name: "War Cleric", group: "Classes", icon: "lorc_mace-head", color: "#c9a227" },
  { id: "nature-cleric", name: "Nature Cleric", group: "Classes", icon: "delapouite_oak-leaf", color: "#7cc35a" },
  { id: "rogue", name: "Rogue", group: "Classes", icon: "lorc_plain-dagger", color: "#8e9aaf" },
  { id: "monk", name: "Monk", group: "Classes", icon: "lorc_fist", color: "#e8964a" },
  { id: "mage", name: "Mage", group: "Classes", icon: "lorc_rune-stone", color: "#5b9cf0" },
  { id: "shaman", name: "Shaman", group: "Classes", icon: "delapouite_totem", color: "#b07cdb" },
  { id: "necromancer", name: "Necromancer", group: "NPC classes", icon: "lorc_evil-book", color: "#7a5ba8" },
  { id: "death-knight", name: "Death Knight", group: "NPC classes", icon: "lorc_dread-skull", color: "#9b2335" },
  { id: "bog-witch", name: "Bog Witch", group: "NPC classes", icon: "lorc_cauldron", color: "#5f8f4a" },
];
